#!/bin/bash
#
# Project       :   isthisevil - Is This Evil?
# Filename      :   rbl_list.sh
# Description   :   Exports a list of Realtime Blackhole List (RBL)
# Author        :   Dreアm @ https://github.com/colorful-dream
# Created       :   August 7th 2016
# Last revision :   August 28th 2017
# Licence       :   MIT licensed, see LICENSE.md 
#
#=============================================================================#

# Exports the variable to whom called it
RBL_SOURCE="
	0spam-killlist.fusionzero.com
	0spam.fusionzero.com
	0spamurl.fusionzero.com
	abuse.rfc-clueless.org
	access.redhawk.org
	all.rbl.jp
	all.rbl.webiron.net
	all.s5h.net
	all.spam-rbl.fr
	all.spamrats.com
	aspews.ext.sorbs.net
	b.barracudacentral.org
	babl.rbl.webiron.net
	backscatter.spameatingmonkey.net
	bad.psky.me
	badconf.rhsbl.sorbs.net
	badnets.spameatingmonkey.net
	bb.barracudacentral.org
	bl.blocklist.de
	bl.drmx.org
	bl.fmb.la
	bl.konstant.no
	bl.nszones.com
	bl.spamcannibal.org
	bl.spamcop.net
	bl.spameatingmonkey.net
	bl.spamstinks.com
	black.junkemailfilter.com
	black.uribl.com
	blackholes.five-ten-sg.com
	blacklist.hostkarma.com
	blacklist.sci.kun.nl
	blacklist.woody.ch
	block.dnsbl.sorbs.net
	bogons.cymru.com
	bogusmx.rfc-clueless.org
	bsb.empty.us
	bsb.spamlookup.net
	cabl.rbl.webiron.net
	cart00ney.surriel.com
	cbl.abuseat.org
	cbl.anti-spam.org.cn
	cblless.anti-spam.org.cn
	cblplus.anti-spam.org.cn
	cdl.anti-spam.org.cn
	cidr.bl.mcafee.com
	combined.rbl.msrbl.net
	communicado.fmb.la
	contacts.abuse.net
	crawler.rbl.webiron.net
	db.wpbl.info
	dbl.spamhaus.org
	dbl.suomispam.net
	dev.null.dk
	dialups.visi.com
	dnsbl-0.uceprotect.net
	dnsbl-1.uceprotect.net
	dnsbl-2.uceprotect.net
	dnsbl-3.uceprotect.net
	dnsbl.abyan.es
	dnsbl.anticaptcha.net
	dnsbl.aspnet.hu
	dnsbl.cobion.com
	dnsbl.inps.de
	dnsbl.justspam.org
	dnsbl.kempt.net
	dnsbl.madavi.de
	dnsbl.othello.ch
	dnsbl.rizon.net
	dnsbl.rv-soft.info
	dnsbl.rymsho.ru
	dnsbl.sorbs.net
	dnsbl.spfbl.net
	dnsbl.zapbl.net
	dnsrbl.org
	dnsrbl.swinog.ch
	dnswl.spfbl.net
	dob.sibl.support-intelligence.net
	dsn.rfc-clueless.org
	dul.dnsbl.sorbs.net
	dul.pacifier.net
	dyn.nszones.com
	dyna.spamrats.com
	dyndns.rbl.jp
	elitist.rfc-clueless.org
	escalations.dnsbl.sorbs.net
	ex.dnsbl.org
	fnrbl.fast.net
	fresh.spameatingmonkey.net
	fresh10.spameatingmonkey.net
	fresh15.spameatingmonkey.net
	fulldom.rfc-clueless.org
	grey.uribl.com
	hostkarma.junkemailfilter.com
	http.dnsbl.sorbs.net
	iddb.isipp.com
	images.rbl.msrbl.net
	in.dnsbl.org
	ips.backscatterer.org
	ix.dnsbl.manitu.net
	korea.services.net
	l1.apews.org
	l2.bbfh.ext.sorbs.net
	l3.bbfh.ext.sorbs.net
	l4.bbfh.ext.sorbs.net
	list.anonwhois.net
	list.bbfh.org
	list.blogspambl.com
	mail-abuse.blacklist.jippg.org
	mailsl.dnsbl.rjek.com
	misc.dnsbl.sorbs.net
	multi.surbl.org
	multi.uribl.com
	netbl.spameatingmonkey.net
	netscan.rbl.blockedservers.com
	new.spam.dnsbl.sorbs.net
	no-more-funn.moensted.dk
	nobl.junkemailfilter.com
	nomail.rhsbl.sorbs.net
	noptr.spamrats.com
	noservers.dnsbl.sorbs.net
	nsbl.fmb.la
	old.spam.dnsbl.sorbs.net
	orvedb.aupads.org
	pbl.spamhaus.org
	phishing.rbl.msrbl.net
	pofon.foobar.hu
	postmaster.rfc-clueless.org
	psbl.surriel.com
	public.sarbl.org
	rbl.abuse.ro
	rbl.blockedservers.com
	rbl.dns-servicios.com
	rbl.efnet.org
	rbl.efnetrbl.org
	rbl.iprange.net
	rbl.megarbl.net
	rbl.schulte.org
	rbl.talkactive.net
	rbl2.triumf.ca
	recent.spam.dnsbl.sorbs.net
	red.uribl.com
	reputation-domain.rbl.scrolloutf1.com
	reputation-ns.rbl.scrolloutf1.com
	rhsbl.rymsho.ru
	rhsbl.scientificspam.net
	rhsbl.sorbs.net
	rhsbl.zapbl.net
	rsbl.aupads.org
	sa.fmb.la
	safe.dnsbl.sorbs.net
	sbl-xbl.spamhaus.org
	sbl.nszones.com
	sbl.spamhaus.org
	short.fmb.la
	short.rbl.jp
	smtp.dnsbl.sorbs.net
	socks.dnsbl.sorbs.net
	spam.dnsbl.anonmails.de
	spam.dnsbl.sorbs.net
	spam.pedantic.org
	spam.rbl.blockedservers.com
	spam.rbl.msrbl.net
	spam.spamrats.com
	spamrbl.imp.ch
	spamsources.fabel.dk
	spamtrap.drbl.drand.net
	srnblack.surgate.net
	st.technovision.dk
	stabl.rbl.webiron.net
	tor.dan.me.uk
	tor.dnsbl.sectoor.de
	tor.efnet.org
	torexit.dan.me.uk
	truncate.gbudb.net
	ubl.nszones.com
	ubl.unsubscore.com
	uri.blacklist.woody.ch
	uribl.abuse.ro
	uribl.pofon.foobar.hu
	uribl.spameatingmonkey.net
	uribl.swinog.ch
	uribl.zeustracker.abuse.ch
	urired.spameatingmonkey.net
	url.rbl.jp
	urlsl.dnsbl.rjek.com
	virbl.dnsbl.bit.nl
	virus.rbl.jp
	virus.rbl.msrbl.net
	vote.drbl.caravan.ru
	vote.drbl.gremlin.ru
	web.dnsbl.sorbs.net
	web.rbl.msrbl.net
	white.uribl.com
	whois.rfc-clueless.org
	work.drbl.caravan.ru
	work.drbl.gremlin.ru
	wormrbl.imp.ch
	xbl.spamhaus.org
	zen.spamhaus.org
	zombie.dnsbl.sorbs.net
	_vouch.dwl.spamhaus.org
"
